### ISSUE TITLE
Load Connection References Add Duplicates to the List

### ISSUE THREAD

**Issue by LinnZawWin** [amar4u30/Amend-Connection-Reference#1]
Clicking on the **Load Cloud Flows and Connection References** button again does not remove the existing items in the Connection Reference combo box, so the list keeps growing with duplicate entries.

![image](https://github.com/amar4u30/Amend-Connection-Reference/assets/14156926/e49e72a4-8e71-446d-b77d-c05a82dbc8f7)

**Comment by amar4u30** [comment]
Resolved this issue.
