### ISSUE TITLE
[Enhancement] Show the connectionreferencelogicalname in Connection Reference List

### ISSUE THREAD

**Issue by LinnZawWin** [amar4u30/Amend-Connection-Reference#4]
If there are multiple Connection References with the same display name, it would be great to show connectionreferencelogicalname in addition to the Connection Reference display name in the List.

e.g. Microsoft Dataverse (msdynce_sharedcommondataserviceforapps_3e6ce)

**Comment by amar4u30** [comment]
Added this Enhancement.
