### ISSUE TITLE
Not able to download tool

### ISSUE THREAD

**Issue by DynamicsCEGeek** [amar4u30/Amend-Connection-Reference#6]
After clicking on Install, run window appears and completes installation, however, when try to launch the tool, it's not appearing. Under the folder, no files exist. 

C:\Users\users\AppData\Roaming\MscrmTools\XrmToolBox\NugetPlugins\AmendConnectionReference.1.0.0.6

![image](https://github.com/amar4u30/Amend-Connection-Reference/assets/134584968/0e48522c-6986-4c81-8859-a7b0771e0c7b)

**Comment by amar4u30** [comment]
There seems to be an issue with New Tool Library, Please switch to Legacy Tool Library and try.
Refer this for the steps to switch: https://www.xrmtoolbox.com/documentation/for-users/xrmtoolbox-settings/
